name: Build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
                  check-latest: true
                  cache: false
            - name: Build
              run: |
                  go mod tidy
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o server_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o server_linux_amd64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o server_linux_arm64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o server_darwin_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o server_darwin_arm64
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  title: Development Build
                  prerelease: true
                  files: |
                      server_windows_amd64.exe
                      server_linux_amd64
                      server_linux_arm64
                      server_darwin_amd64
                      server_darwin_arm64
    frontend:
           name: Front-end
           runs-on: ubuntu-latest
           steps:
                  - uses: actions/checkout@v4
                  - uses: actions/setup-node@v4
                    with:
                        node-version: 22
                        cache: 'yarn'
                        cache-dependency-path: ./web/yarn.lock
                        check-latest: true
                  - run: yarn install && yarn build
                    working-directory: ./web

                  - uses: actions/upload-artifact@v4
                    with:
                         compression-level: 9
                         name: static-assets
                         path: web/build
